// Generated by the Rust IPC contract test; edit the DTOs, not this fixture.
import type { IpcContractFixtures } from "./types";

export const ipcContractFixtures = {
  "snapshot": {
    "config": {
      "schema_version": 5,
      "preferences": {
        "timezone": "Asia/Tbilisi",
        "autostart": true,
        "paused": false,
        "orientation": "landscape-flipped"
      },
      "cards": [
        {
          "kind": "clock",
          "id": "clock",
          "title": "Desk",
          "show_seconds": true,
          "template": {
            "kind": "digital-clock"
          },
          "tap_action": {
            "kind": "none"
          },
          "refresh": {
            "kind": "device-local"
          },
          "alert": {
            "kind": "none"
          }
        },
        {
          "kind": "pomodoro",
          "id": "pomodoro",
          "label": "Focus",
          "duration_seconds": 1500,
          "template": {
            "kind": "progress-ring"
          },
          "tap_action": {
            "kind": "start-pause"
          },
          "refresh": {
            "kind": "device-local"
          },
          "alert": {
            "kind": "on-timer-finish",
            "hold": {
              "kind": "until-dismissed"
            }
          }
        },
        {
          "kind": "calendar",
          "id": "calendar",
          "title": "Next",
          "source": {
            "kind": "file",
            "value": "/tmp/calendar.ics"
          },
          "template": {
            "kind": "row-list"
          },
          "tap_action": {
            "kind": "none"
          },
          "refresh": {
            "kind": "interval",
            "minutes": 15
          },
          "alert": {
            "kind": "before-event",
            "lead_minutes": 5,
            "hold": {
              "kind": "seconds",
              "value": 60
            }
          }
        }
      ],
      "assets": [],
      "playlists": [
        {
          "id": "workday",
          "name": "Workday",
          "advance": {
            "kind": "timed",
            "default_dwell_seconds": 30
          },
          "entries": [
            {
              "card_id": "clock",
              "dwell_seconds": null
            },
            {
              "card_id": "pomodoro",
              "dwell_seconds": 20
            },
            {
              "card_id": "calendar",
              "dwell_seconds": null
            }
          ]
        },
        {
          "id": "manual",
          "name": "Manual",
          "advance": {
            "kind": "manual"
          },
          "entries": [
            {
              "card_id": "clock",
              "dwell_seconds": null
            }
          ]
        }
      ],
      "active_playlist_id": "workday",
      "updater": {
        "channel": "stable",
        "checks": "notify"
      }
    },
    "runtime": {
      "kind": "error",
      "message": "example runtime error"
    },
    "device": {
      "connection": {
        "kind": "disconnected",
        "reason": "USB disconnected"
      },
      "port_name": "/dev/cu.usbmodem1",
      "firmware_version": "1.0.0",
      "protocol_version": 1,
      "max_protocol_version": 1,
      "capabilities": [
        "core-widgets"
      ],
      "unknown_capability_bits": "0x0000000000000000",
      "uptime_ms": 42,
      "free_heap": 123456,
      "rotation": 90,
      "tier": null,
      "wifi_state": null,
      "wifi_rssi": null,
      "ip": null,
      "last_network_error": null,
      "ota_state": null,
      "active_screen_id": "clock",
      "counters": {
        "host_reconnects": 1,
        "valid_frames": 2,
        "malformed_frames": 3,
        "crc_errors": 4,
        "overflow_frames": 5,
        "dropped_responses": 6,
        "rx_dropped_bytes": 7,
        "dropped_events": 8,
        "event_queue_high_water": 9,
        "dropped_ui_commands": 10,
        "ui_queue_high_water": 11,
        "host_dropped_events": 12,
        "detected_event_gaps": 13
      }
    },
    "providers": [
      {
        "widget_id": "calendar",
        "state": {
          "kind": "stale",
          "message": "offline"
        },
        "last_success_unix_ms": 1786000000000,
        "age_seconds": 120
      }
    ],
    "pomodoros": [
      {
        "widget_id": "pomodoro",
        "state": "running",
        "duration_seconds": 1500,
        "remaining_seconds": 900
      }
    ],
    "card_data": [
      {
        "card_id": "calendar",
        "fields": [
          {
            "key": "row0_title",
            "value": {
              "kind": "text",
              "value": "Design review"
            }
          },
          {
            "key": "next_start_unix_ms",
            "value": {
              "kind": "integer",
              "value": 1787000000000
            }
          },
          {
            "key": "stale",
            "value": {
              "kind": "boolean",
              "value": false
            }
          }
        ]
      }
    ],
    "card_errors": [
      {
        "card_id": "json",
        "message": "the display refused this card's data (InvalidPayload): invalid push data"
      }
    ],
    "persistence": {
      "kind": "validation-failed",
      "message": "Your saved settings failed validation and were not applied",
      "issues": [
        {
          "path": "active_playlist_id",
          "code": "missing-reference",
          "message": "active playlist does not exist"
        }
      ]
    },
    "diagnostics": {
      "commands_processed": 1,
      "command_queue_full": 2,
      "provider_jobs_started": 3,
      "provider_queue_full": 4,
      "provider_results_discarded": 5,
      "subscriber_snapshots_overwritten": 6,
      "interrupt_dismissals_ignored": 7
    },
    "has_saved_config": true
  },
  "configs": [
    {
      "schema_version": 5,
      "preferences": {
        "timezone": "Asia/Tbilisi",
        "autostart": true,
        "paused": false,
        "orientation": "landscape-flipped"
      },
      "cards": [
        {
          "kind": "clock",
          "id": "clock",
          "title": "Desk",
          "show_seconds": true,
          "template": {
            "kind": "digital-clock"
          },
          "tap_action": {
            "kind": "none"
          },
          "refresh": {
            "kind": "device-local"
          },
          "alert": {
            "kind": "none"
          }
        },
        {
          "kind": "pomodoro",
          "id": "pomodoro",
          "label": "Focus",
          "duration_seconds": 1500,
          "template": {
            "kind": "progress-ring"
          },
          "tap_action": {
            "kind": "start-pause"
          },
          "refresh": {
            "kind": "device-local"
          },
          "alert": {
            "kind": "on-timer-finish",
            "hold": {
              "kind": "until-dismissed"
            }
          }
        },
        {
          "kind": "calendar",
          "id": "calendar",
          "title": "Next",
          "source": {
            "kind": "file",
            "value": "/tmp/calendar.ics"
          },
          "template": {
            "kind": "row-list"
          },
          "tap_action": {
            "kind": "none"
          },
          "refresh": {
            "kind": "interval",
            "minutes": 15
          },
          "alert": {
            "kind": "before-event",
            "lead_minutes": 5,
            "hold": {
              "kind": "seconds",
              "value": 60
            }
          }
        }
      ],
      "assets": [],
      "playlists": [
        {
          "id": "workday",
          "name": "Workday",
          "advance": {
            "kind": "timed",
            "default_dwell_seconds": 30
          },
          "entries": [
            {
              "card_id": "clock",
              "dwell_seconds": null
            },
            {
              "card_id": "pomodoro",
              "dwell_seconds": 20
            },
            {
              "card_id": "calendar",
              "dwell_seconds": null
            }
          ]
        },
        {
          "id": "manual",
          "name": "Manual",
          "advance": {
            "kind": "manual"
          },
          "entries": [
            {
              "card_id": "clock",
              "dwell_seconds": null
            }
          ]
        }
      ],
      "active_playlist_id": "workday",
      "updater": {
        "channel": "stable",
        "checks": "notify"
      }
    }
  ],
  "card_settings": [
    {
      "kind": "clock",
      "id": "clock",
      "title": "Desk",
      "show_seconds": true,
      "template": {
        "kind": "digital-clock"
      },
      "tap_action": {
        "kind": "none"
      },
      "refresh": {
        "kind": "device-local"
      },
      "alert": {
        "kind": "none"
      }
    },
    {
      "kind": "pomodoro",
      "id": "pomodoro",
      "label": "Focus",
      "duration_seconds": 1500,
      "template": {
        "kind": "progress-ring"
      },
      "tap_action": {
        "kind": "start-pause"
      },
      "refresh": {
        "kind": "device-local"
      },
      "alert": {
        "kind": "on-timer-finish",
        "hold": {
          "kind": "until-dismissed"
        }
      }
    },
    {
      "kind": "calendar",
      "id": "calendar",
      "title": "Next",
      "source": {
        "kind": "file",
        "value": "/tmp/calendar.ics"
      },
      "template": {
        "kind": "row-list"
      },
      "tap_action": {
        "kind": "none"
      },
      "refresh": {
        "kind": "interval",
        "minutes": 15
      },
      "alert": {
        "kind": "before-event",
        "lead_minutes": 5,
        "hold": {
          "kind": "seconds",
          "value": 60
        }
      }
    },
    {
      "kind": "weather",
      "id": "weather",
      "title": "Weather",
      "location": "Tbilisi",
      "units": "metric",
      "template": {
        "kind": "icon-badge-text",
        "icon_asset_id": "weather-icons"
      },
      "tap_action": {
        "kind": "open-url",
        "url": "https://example.test/weather"
      },
      "refresh": {
        "kind": "interval",
        "minutes": 30
      },
      "alert": {
        "kind": "none"
      }
    },
    {
      "kind": "json-feed",
      "id": "json",
      "title": "Metric",
      "url": "https://example.test/metric.json",
      "mappings": [
        {
          "field": "value",
          "path": "$.current.value"
        }
      ],
      "template": {
        "kind": "big-number-label"
      },
      "tap_action": {
        "kind": "open-application",
        "application_id": "com.example.metrics"
      },
      "refresh": {
        "kind": "manual"
      },
      "alert": {
        "kind": "none"
      }
    },
    {
      "kind": "rss",
      "id": "news",
      "title": "News",
      "url": "https://example.test/feed.xml",
      "max_items": 3,
      "template": {
        "kind": "row-list"
      },
      "tap_action": {
        "kind": "dismiss"
      },
      "refresh": {
        "kind": "interval",
        "minutes": 15
      },
      "alert": {
        "kind": "none"
      }
    }
  ],
  "playlists": [
    {
      "id": "workday",
      "name": "Workday",
      "advance": {
        "kind": "timed",
        "default_dwell_seconds": 30
      },
      "entries": [
        {
          "card_id": "clock",
          "dwell_seconds": null
        },
        {
          "card_id": "pomodoro",
          "dwell_seconds": 20
        },
        {
          "card_id": "calendar",
          "dwell_seconds": null
        }
      ]
    },
    {
      "id": "manual",
      "name": "Manual",
      "advance": {
        "kind": "manual"
      },
      "entries": [
        {
          "card_id": "clock",
          "dwell_seconds": null
        }
      ]
    }
  ],
  "playlist_entries": [
    {
      "card_id": "clock",
      "dwell_seconds": null
    },
    {
      "card_id": "pomodoro",
      "dwell_seconds": 20
    },
    {
      "card_id": "calendar",
      "dwell_seconds": null
    }
  ],
  "card_alerts": [
    {
      "kind": "none"
    },
    {
      "kind": "on-timer-finish",
      "hold": {
        "kind": "until-dismissed"
      }
    },
    {
      "kind": "before-event",
      "lead_minutes": 5,
      "hold": {
        "kind": "seconds",
        "value": 60
      }
    }
  ],
  "alert_holds": [
    {
      "kind": "until-dismissed"
    },
    {
      "kind": "seconds",
      "value": 60
    }
  ],
  "carousel_advances": [
    {
      "kind": "manual"
    },
    {
      "kind": "timed",
      "default_dwell_seconds": 20
    }
  ],
  "calendar_sources": [
    {
      "kind": "file",
      "value": "/tmp/calendar.ics"
    },
    {
      "kind": "url",
      "value": "https://example.test/calendar.ics"
    }
  ],
  "display_templates": [
    {
      "kind": "digital-clock"
    },
    {
      "kind": "analog-clock"
    },
    {
      "kind": "progress-ring"
    },
    {
      "kind": "row-list"
    },
    {
      "kind": "big-number-label"
    },
    {
      "kind": "icon-badge-text",
      "icon_asset_id": "weather-icons"
    }
  ],
  "tap_actions": [
    {
      "kind": "none"
    },
    {
      "kind": "start-pause"
    },
    {
      "kind": "reset"
    },
    {
      "kind": "dismiss"
    },
    {
      "kind": "open-url",
      "url": "https://example.test/action"
    },
    {
      "kind": "open-application",
      "application_id": "com.example.app"
    }
  ],
  "refresh_policies": [
    {
      "kind": "device-local"
    },
    {
      "kind": "manual"
    },
    {
      "kind": "interval",
      "minutes": 15
    }
  ],
  "weather_units": [
    "metric",
    "imperial"
  ],
  "asset_sources": [
    {
      "kind": "file",
      "value": "/tmp/weather-icons.ttf"
    }
  ],
  "asset_kinds": [
    {
      "kind": "font"
    },
    {
      "kind": "icon-font",
      "glyphs": [
        {
          "name": "cloud-rain",
          "codepoint": 63273
        }
      ]
    },
    {
      "kind": "image"
    }
  ],
  "update_channels": [
    "stable",
    "beta",
    "manual"
  ],
  "update_check_policies": [
    "disabled",
    "notify"
  ],
  "firmware_artifacts": [
    {
      "version": "1.0.0",
      "model": "waveshare-1.8",
      "byte_length": 524288,
      "sha256_hex": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
      "signing_key_id": "deskmate-release-1",
      "signature_base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    }
  ],
  "display_orientations": [
    "landscape",
    "landscape-flipped"
  ],
  "device_capabilities": [
    "core-widgets",
    "config-rotation",
    "dashboard-layouts",
    "extended-templates",
    "host-tap-actions",
    "asset-transfer",
    "firmware-update",
    "networking",
    "scene-render"
  ],
  "runtime_states": [
    {
      "kind": "starting"
    },
    {
      "kind": "running"
    },
    {
      "kind": "paused"
    },
    {
      "kind": "error",
      "message": "error"
    }
  ],
  "connection_states": [
    {
      "kind": "disconnected",
      "reason": null
    },
    {
      "kind": "connecting"
    },
    {
      "kind": "online"
    },
    {
      "kind": "standalone"
    }
  ],
  "provider_states": [
    {
      "kind": "idle"
    },
    {
      "kind": "refreshing"
    },
    {
      "kind": "fresh"
    },
    {
      "kind": "stale",
      "message": "stale"
    },
    {
      "kind": "error",
      "message": "error"
    }
  ],
  "pomodoro_states": [
    "idle",
    "running",
    "paused",
    "completed"
  ],
  "card_data": [
    {
      "card_id": "calendar",
      "fields": [
        {
          "key": "row0_title",
          "value": {
            "kind": "text",
            "value": "Design review"
          }
        },
        {
          "key": "next_start_unix_ms",
          "value": {
            "kind": "integer",
            "value": 1787000000000
          }
        },
        {
          "key": "stale",
          "value": {
            "kind": "boolean",
            "value": false
          }
        }
      ]
    }
  ],
  "persistence_states": [
    {
      "kind": "clean"
    },
    {
      "kind": "saving"
    },
    {
      "kind": "recoverable-error",
      "message": "error"
    },
    {
      "kind": "validation-failed",
      "message": "Your saved settings failed validation and were not applied",
      "issues": [
        {
          "path": "active_playlist_id",
          "code": "missing-reference",
          "message": "active playlist does not exist"
        }
      ]
    }
  ],
  "validation_codes": [
    "unsupported-version",
    "empty",
    "too-long",
    "too-many",
    "duplicate-id",
    "missing-reference",
    "missing-screen",
    "duplicate-reference",
    "unsupported-size",
    "out-of-range",
    "invalid-timezone",
    "invalid-source",
    "invalid-composition",
    "overlap",
    "too-large",
    "requires-capability"
  ],
  "pomodoro_actions": [
    "start",
    "pause",
    "toggle",
    "reset"
  ],
  "errors": [
    {
      "category": "invalid-payload",
      "message": "invalid"
    },
    {
      "category": "payload-too-large",
      "message": "large",
      "maximum_bytes": 65536
    },
    {
      "category": "validation",
      "message": "validation",
      "issues": [
        {
          "path": "active_playlist_id",
          "code": "missing-reference",
          "message": "active playlist does not exist"
        }
      ]
    },
    {
      "category": "persistence",
      "message": "persistence"
    },
    {
      "category": "runtime-busy",
      "message": "busy"
    },
    {
      "category": "runtime-unavailable",
      "message": "unavailable"
    },
    {
      "category": "not-found",
      "message": "missing"
    },
    {
      "category": "device",
      "message": "device"
    },
    {
      "category": "provider",
      "message": "provider"
    },
    {
      "category": "autostart",
      "message": "autostart"
    },
    {
      "category": "window",
      "message": "window"
    },
    {
      "category": "internal",
      "message": "internal"
    }
  ],
  "draft_validation": {
    "valid": false,
    "issues": [
      {
        "path": "active_playlist_id",
        "code": "missing-reference",
        "message": "active playlist does not exist"
      }
    ]
  },
  "config_apply_result": {
    "save": {
      "generation": 7,
      "warning": {
        "kind": "io",
        "operation": "sync config directory",
        "message": "example warning"
      }
    }
  },
  "autostart_status": {
    "enabled": true,
    "preference_enabled": false
  },
  "preview_frame": {
    "png_base64": "iVBORw0KGgo=",
    "sample": true
  }
} as const satisfies IpcContractFixtures;
