// Generated by the Rust contract test; edit the DTOs, not this fixture.
import type { ApiContractFixtures } from "./types";

export const apiContractFixtures = {
  "snapshot": {
    "config": {
      "schema_version": 10,
      "preferences": {
        "timezone": "Asia/Tbilisi",
        "autostart": true,
        "paused": false,
        "orientation": "landscape-flipped"
      },
      "cards": [
        {
          "kind": "clock",
          "id": "clock",
          "title": "Desk",
          "show_seconds": true,
          "template": {
            "kind": "digital-clock"
          },
          "tap_action": {
            "kind": "none"
          },
          "refresh": {
            "kind": "device-local"
          },
          "alert": {
            "kind": "none"
          },
          "dwell_seconds": null
        },
        {
          "kind": "pomodoro",
          "id": "pomodoro",
          "label": "Focus",
          "duration_seconds": 1500,
          "template": {
            "kind": "progress-ring"
          },
          "tap_action": {
            "kind": "start-pause"
          },
          "refresh": {
            "kind": "device-local"
          },
          "alert": {
            "kind": "on-timer-finish",
            "hold": {
              "kind": "until-dismissed"
            }
          },
          "dwell_seconds": null
        },
        {
          "kind": "picture",
          "id": "limits-picture",
          "title": "Limits",
          "source_id": "limits",
          "tap_action": {
            "kind": "none"
          },
          "refresh": {
            "kind": "manual"
          },
          "alert": {
            "kind": "none"
          },
          "dwell_seconds": null
        }
      ],
      "image_sources": [
        {
          "id": "limits",
          "name": "Claude limits"
        }
      ],
      "assets": [],
      "advance": {
        "kind": "timed",
        "default_dwell_seconds": 30
      },
      "updater": {
        "channel": "stable",
        "checks": "notify"
      }
    },
    "runtime": {
      "kind": "error",
      "message": "example runtime error"
    },
    "device": {
      "connection": {
        "kind": "disconnected",
        "reason": "the display is not linked to the server"
      },
      "port_name": null,
      "firmware_version": "1.0.0",
      "protocol_version": 2,
      "max_protocol_version": 2,
      "capabilities": [
        "scene-render"
      ],
      "unknown_capability_bits": "0x0000000000000000",
      "uptime_ms": 42,
      "free_heap": 123456,
      "rotation": 90,
      "tier": null,
      "wifi_state": null,
      "wifi_rssi": null,
      "ip": null,
      "last_network_error": null,
      "ota_state": null,
      "active_card_id": "clock",
      "counters": {
        "host_reconnects": 1,
        "valid_frames": 2,
        "malformed_frames": 3,
        "crc_errors": 4,
        "overflow_frames": 5,
        "dropped_responses": 6,
        "rx_dropped_bytes": 7,
        "dropped_events": 8,
        "event_queue_high_water": 9,
        "dropped_ui_commands": 10,
        "ui_queue_high_water": 11,
        "host_dropped_events": 12,
        "detected_event_gaps": 13
      }
    },
    "pomodoros": [
      {
        "card_id": "pomodoro",
        "state": "running",
        "duration_seconds": 1500,
        "remaining_seconds": 900
      }
    ],
    "card_data": [
      {
        "card_id": "limits-picture",
        "fields": [
          {
            "key": "summary",
            "value": {
              "kind": "text",
              "value": "42 · Good"
            }
          },
          {
            "key": "stale",
            "value": {
              "kind": "boolean",
              "value": false
            }
          }
        ]
      }
    ],
    "card_errors": [
      {
        "kind": "data-refused",
        "card_id": "pomodoro",
        "message": "the display refused this card's timer (InvalidPayload): invalid push data"
      }
    ],
    "persistence": {
      "kind": "validation-failed",
      "message": "Your saved settings failed validation and were not applied",
      "issues": [
        {
          "path": "cards[1].duration_seconds",
          "code": "out-of-range",
          "message": "duration must be 1..=86400 seconds"
        }
      ]
    },
    "diagnostics": {
      "commands_processed": 1,
      "command_queue_full": 2,
      "subscriber_snapshots_overwritten": 6,
      "interrupt_dismissals_ignored": 7
    },
    "has_saved_config": true,
    "host_protocol_version": 2
  },
  "configs": [
    {
      "schema_version": 10,
      "preferences": {
        "timezone": "Asia/Tbilisi",
        "autostart": true,
        "paused": false,
        "orientation": "landscape-flipped"
      },
      "cards": [
        {
          "kind": "clock",
          "id": "clock",
          "title": "Desk",
          "show_seconds": true,
          "template": {
            "kind": "digital-clock"
          },
          "tap_action": {
            "kind": "none"
          },
          "refresh": {
            "kind": "device-local"
          },
          "alert": {
            "kind": "none"
          },
          "dwell_seconds": null
        },
        {
          "kind": "pomodoro",
          "id": "pomodoro",
          "label": "Focus",
          "duration_seconds": 1500,
          "template": {
            "kind": "progress-ring"
          },
          "tap_action": {
            "kind": "start-pause"
          },
          "refresh": {
            "kind": "device-local"
          },
          "alert": {
            "kind": "on-timer-finish",
            "hold": {
              "kind": "until-dismissed"
            }
          },
          "dwell_seconds": null
        },
        {
          "kind": "picture",
          "id": "limits-picture",
          "title": "Limits",
          "source_id": "limits",
          "tap_action": {
            "kind": "none"
          },
          "refresh": {
            "kind": "manual"
          },
          "alert": {
            "kind": "none"
          },
          "dwell_seconds": null
        }
      ],
      "image_sources": [
        {
          "id": "limits",
          "name": "Claude limits"
        }
      ],
      "assets": [],
      "advance": {
        "kind": "timed",
        "default_dwell_seconds": 30
      },
      "updater": {
        "channel": "stable",
        "checks": "notify"
      }
    }
  ],
  "card_settings": [
    {
      "kind": "clock",
      "id": "clock",
      "title": "Desk",
      "show_seconds": true,
      "template": {
        "kind": "digital-clock"
      },
      "tap_action": {
        "kind": "none"
      },
      "refresh": {
        "kind": "device-local"
      },
      "alert": {
        "kind": "none"
      },
      "dwell_seconds": null
    },
    {
      "kind": "pomodoro",
      "id": "pomodoro",
      "label": "Focus",
      "duration_seconds": 1500,
      "template": {
        "kind": "progress-ring"
      },
      "tap_action": {
        "kind": "start-pause"
      },
      "refresh": {
        "kind": "device-local"
      },
      "alert": {
        "kind": "on-timer-finish",
        "hold": {
          "kind": "until-dismissed"
        }
      },
      "dwell_seconds": null
    },
    {
      "kind": "picture",
      "id": "limits-picture",
      "title": "Limits",
      "source_id": "limits",
      "tap_action": {
        "kind": "none"
      },
      "refresh": {
        "kind": "manual"
      },
      "alert": {
        "kind": "none"
      },
      "dwell_seconds": null
    }
  ],
  "card_alerts": [
    {
      "kind": "none"
    },
    {
      "kind": "on-timer-finish",
      "hold": {
        "kind": "until-dismissed"
      }
    }
  ],
  "alert_holds": [
    {
      "kind": "until-dismissed"
    },
    {
      "kind": "seconds",
      "value": 60
    }
  ],
  "carousel_advances": [
    {
      "kind": "manual"
    },
    {
      "kind": "timed",
      "default_dwell_seconds": 20
    }
  ],
  "display_templates": [
    {
      "kind": "digital-clock"
    },
    {
      "kind": "analog-clock"
    },
    {
      "kind": "progress-ring"
    }
  ],
  "tap_actions": [
    {
      "kind": "none"
    },
    {
      "kind": "start-pause"
    },
    {
      "kind": "reset"
    },
    {
      "kind": "dismiss"
    },
    {
      "kind": "open-url",
      "url": "https://example.test/action"
    },
    {
      "kind": "open-application",
      "application_id": "com.example.app"
    }
  ],
  "refresh_policies": [
    {
      "kind": "device-local"
    },
    {
      "kind": "manual"
    },
    {
      "kind": "interval",
      "minutes": 15
    }
  ],
  "asset_sources": [
    {
      "kind": "file",
      "value": "/tmp/status-icons.ttf"
    }
  ],
  "asset_kinds": [
    {
      "kind": "font"
    },
    {
      "kind": "icon-font",
      "glyphs": [
        {
          "name": "cloud-rain",
          "codepoint": 63273
        }
      ]
    },
    {
      "kind": "image"
    }
  ],
  "update_channels": [
    "stable",
    "beta",
    "manual"
  ],
  "update_check_policies": [
    "disabled",
    "notify"
  ],
  "display_orientations": [
    "landscape",
    "landscape-flipped"
  ],
  "device_capabilities": [
    "asset-transfer",
    "firmware-update",
    "networking",
    "scene-render",
    "volatile-assets",
    "durable-asset-encoding"
  ],
  "runtime_states": [
    {
      "kind": "starting"
    },
    {
      "kind": "running"
    },
    {
      "kind": "paused"
    },
    {
      "kind": "error",
      "message": "error"
    }
  ],
  "connection_states": [
    {
      "kind": "disconnected",
      "reason": null
    },
    {
      "kind": "connecting"
    },
    {
      "kind": "online"
    },
    {
      "kind": "standalone"
    }
  ],
  "pomodoro_states": [
    "idle",
    "running",
    "paused",
    "completed"
  ],
  "card_data": [
    {
      "card_id": "limits-picture",
      "fields": [
        {
          "key": "summary",
          "value": {
            "kind": "text",
            "value": "42 · Good"
          }
        },
        {
          "key": "stale",
          "value": {
            "kind": "boolean",
            "value": false
          }
        }
      ]
    }
  ],
  "persistence_states": [
    {
      "kind": "clean"
    },
    {
      "kind": "saving"
    },
    {
      "kind": "recoverable-error",
      "message": "error"
    },
    {
      "kind": "validation-failed",
      "message": "Your saved settings failed validation and were not applied",
      "issues": [
        {
          "path": "cards[1].duration_seconds",
          "code": "out-of-range",
          "message": "duration must be 1..=86400 seconds"
        }
      ]
    }
  ],
  "validation_codes": [
    "unsupported-version",
    "empty",
    "too-long",
    "too-many",
    "duplicate-id",
    "missing-reference",
    "out-of-range",
    "invalid-timezone",
    "invalid-source",
    "invalid-composition",
    "too-large",
    "requires-capability"
  ],
  "pomodoro_actions": [
    "start",
    "pause",
    "toggle",
    "reset"
  ],
  "errors": [
    {
      "category": "invalid-payload",
      "message": "invalid"
    },
    {
      "category": "payload-too-large",
      "message": "large",
      "maximum_bytes": 65536
    },
    {
      "category": "validation",
      "message": "validation",
      "issues": [
        {
          "path": "cards[1].duration_seconds",
          "code": "out-of-range",
          "message": "duration must be 1..=86400 seconds"
        }
      ]
    },
    {
      "category": "persistence",
      "message": "persistence"
    },
    {
      "category": "runtime-unavailable",
      "message": "unavailable"
    },
    {
      "category": "not-found",
      "message": "missing"
    },
    {
      "category": "device",
      "message": "device"
    },
    {
      "category": "internal",
      "message": "internal"
    }
  ],
  "draft_validation": {
    "valid": false,
    "issues": [
      {
        "path": "cards[1].duration_seconds",
        "code": "out-of-range",
        "message": "duration must be 1..=86400 seconds"
      }
    ]
  },
  "config_apply_result": {
    "save": {
      "generation": 7,
      "warning": {
        "kind": "io",
        "operation": "sync config directory",
        "message": "example warning"
      }
    }
  },
  "preview_frame": {
    "png_base64": "iVBORw0KGgo=",
    "sample": true,
    "state": null
  },
  "device_rows": [
    {
      "id": "unconfigured-display",
      "connected": false,
      "has_saved_config": false,
      "configured_at": null
    },
    {
      "id": "configured-display",
      "connected": true,
      "has_saved_config": true,
      "configured_at": 1700000000
    }
  ],
  "mint_source_responses": [
    {
      "id": "fixture-source",
      "token": "fixture-token"
    }
  ],
  "image_source_descriptors": [
    {
      "face": null,
      "face_status": null,
      "id": "external-source",
      "name": "External picture"
    },
    {
      "face": {
        "fields": [
          {
            "key": "location",
            "label": "Location",
            "placeholder": "Dubai",
            "type": "text",
            "value": ""
          },
          {
            "key": "units",
            "label": "Units",
            "options": [
              {
                "label": "Metric",
                "value": "metric"
              },
              {
                "label": "Imperial",
                "value": "imperial"
              }
            ],
            "type": "enum",
            "value": "metric"
          }
        ],
        "kind": "weather",
        "label": "Weather"
      },
      "face_status": {
        "at_unix_seconds": null,
        "message": null,
        "state": "needs-settings"
      },
      "id": "weather-source",
      "name": "Weather"
    },
    {
      "face": {
        "fields": [
          {
            "key": "location",
            "label": "Location",
            "placeholder": "Dubai",
            "type": "text",
            "value": ""
          },
          {
            "key": "units",
            "label": "Units",
            "options": [
              {
                "label": "Metric",
                "value": "metric"
              },
              {
                "label": "Imperial",
                "value": "imperial"
              }
            ],
            "type": "enum",
            "value": "metric"
          }
        ],
        "kind": "weather",
        "label": "Weather"
      },
      "face_status": {
        "at_unix_seconds": 1790000000,
        "message": "the token was not found; check the coin ID",
        "state": "needs-attention"
      },
      "id": "token-source",
      "name": "Token price"
    }
  ],
  "face_descriptors": [
    {
      "kind": "weather",
      "label": "Weather",
      "fields": [
        {
          "type": "text",
          "key": "location",
          "label": "Location",
          "value": "",
          "placeholder": "Dubai"
        },
        {
          "type": "enum",
          "key": "units",
          "label": "Units",
          "value": "metric",
          "options": [
            {
              "value": "metric",
              "label": "Metric"
            },
            {
              "value": "imperial",
              "label": "Imperial"
            }
          ]
        }
      ]
    },
    {
      "kind": "rss",
      "label": "RSS feed",
      "fields": [
        {
          "type": "url",
          "key": "url",
          "label": "Feed URL",
          "value": "",
          "placeholder": "https://example.com/feed.xml"
        },
        {
          "type": "text",
          "key": "title",
          "label": "Title",
          "value": "",
          "placeholder": "News"
        }
      ]
    },
    {
      "kind": "token",
      "label": "Token price",
      "fields": [
        {
          "type": "text",
          "key": "coin_id",
          "label": "Coin ID",
          "value": "",
          "placeholder": "solana"
        },
        {
          "type": "text",
          "key": "currency",
          "label": "Currency",
          "value": "usd",
          "placeholder": "usd"
        }
      ]
    },
    {
      "kind": "headlines",
      "label": "Headlines",
      "tap": "Tap the panel for the next stories.",
      "fields": [
        {
          "type": "enum",
          "key": "list",
          "label": "Stories",
          "value": "top",
          "options": [
            {
              "value": "top",
              "label": "Front page"
            },
            {
              "value": "new",
              "label": "Newest"
            }
          ]
        }
      ]
    }
  ],
  "card_error_kinds": [
    "data-refused",
    "scene-refused"
  ],
  "card_field_values": [
    {
      "kind": "text",
      "value": "text"
    },
    {
      "kind": "integer",
      "value": 42
    },
    {
      "kind": "boolean",
      "value": true
    }
  ],
  "store_warnings": [
    {
      "kind": "io",
      "operation": "write config",
      "message": "example warning"
    }
  ],
  "device_tiers": [
    "local",
    "networked"
  ],
  "device_wifi_states": [
    "down",
    "connecting",
    "connected",
    "failed"
  ],
  "device_ota_states": [
    "idle",
    "checking",
    "downloading",
    "pending-verify",
    "failed"
  ],
  "face_field_descriptors": [
    {
      "type": "text",
      "key": "location",
      "label": "Location",
      "value": "",
      "placeholder": "Dubai"
    },
    {
      "type": "url",
      "key": "url",
      "label": "Feed URL",
      "value": "",
      "placeholder": "https://example.com/feed.xml"
    },
    {
      "type": "enum",
      "key": "units",
      "label": "Units",
      "value": "metric",
      "options": [
        {
          "value": "metric",
          "label": "Metric"
        },
        {
          "value": "imperial",
          "label": "Imperial"
        }
      ]
    }
  ]
} as const satisfies ApiContractFixtures;
