// Generated by the Rust IPC contract test; edit the DTOs, not this fixture.
import type { IpcContractFixtures } from "./types";

export const ipcContractFixtures = {
  "snapshot": {
    "config": {
      "schema_version": 1,
      "preferences": {
        "timezone": "Asia/Tbilisi",
        "autostart": true,
        "paused": false
      },
      "widgets": [
        {
          "kind": "clock",
          "id": "clock",
          "size": "full",
          "title": "Desk",
          "show_seconds": true
        },
        {
          "kind": "pomodoro",
          "id": "pomodoro",
          "size": "standard",
          "label": "Focus",
          "duration_seconds": 1500
        },
        {
          "kind": "calendar",
          "id": "calendar",
          "size": "standard",
          "title": "Next",
          "source": {
            "kind": "file",
            "value": "/tmp/calendar.ics"
          },
          "refresh_minutes": 15
        }
      ],
      "screens": [
        {
          "id": "clock-screen",
          "widget_id": "clock"
        },
        {
          "id": "pomodoro-screen",
          "widget_id": "pomodoro"
        },
        {
          "id": "calendar-screen",
          "widget_id": "calendar"
        }
      ]
    },
    "runtime": {
      "kind": "error",
      "message": "example runtime error"
    },
    "device": {
      "connection": {
        "kind": "disconnected",
        "reason": "USB disconnected"
      },
      "port_name": "/dev/cu.usbmodem1",
      "firmware_version": "1.0.0",
      "protocol_version": 1,
      "uptime_ms": 42,
      "free_heap": 123456,
      "rotation": 90,
      "active_screen_id": "clock-screen",
      "counters": {
        "reconnects": 1,
        "valid_frames": 2,
        "malformed_frames": 3,
        "crc_errors": 4,
        "overflow_frames": 5,
        "dropped_responses": 6,
        "rx_dropped_bytes": 7,
        "dropped_events": 8,
        "event_queue_high_water": 9,
        "dropped_ui_commands": 10,
        "ui_queue_high_water": 11,
        "host_dropped_events": 12,
        "detected_event_gaps": 13
      }
    },
    "providers": [
      {
        "widget_id": "calendar",
        "state": {
          "kind": "stale",
          "message": "offline"
        },
        "last_success_unix_ms": 1786000000000,
        "age_seconds": 120
      }
    ],
    "pomodoros": [
      {
        "widget_id": "pomodoro",
        "state": "running",
        "duration_seconds": 1500,
        "remaining_seconds": 900
      }
    ],
    "persistence": {
      "kind": "recoverable-error",
      "message": "disk full"
    },
    "diagnostics": {
      "commands_processed": 1,
      "command_queue_full": 2,
      "provider_jobs_started": 3,
      "provider_queue_full": 4,
      "provider_results_discarded": 5,
      "subscriber_snapshots_overwritten": 6
    }
  },
  "configs": [
    {
      "schema_version": 1,
      "preferences": {
        "timezone": "Asia/Tbilisi",
        "autostart": true,
        "paused": false
      },
      "widgets": [
        {
          "kind": "clock",
          "id": "clock",
          "size": "full",
          "title": "Desk",
          "show_seconds": true
        },
        {
          "kind": "pomodoro",
          "id": "pomodoro",
          "size": "standard",
          "label": "Focus",
          "duration_seconds": 1500
        },
        {
          "kind": "calendar",
          "id": "calendar",
          "size": "standard",
          "title": "Next",
          "source": {
            "kind": "file",
            "value": "/tmp/calendar.ics"
          },
          "refresh_minutes": 15
        }
      ],
      "screens": [
        {
          "id": "clock-screen",
          "widget_id": "clock"
        },
        {
          "id": "pomodoro-screen",
          "widget_id": "pomodoro"
        },
        {
          "id": "calendar-screen",
          "widget_id": "calendar"
        }
      ]
    }
  ],
  "widget_settings": [
    {
      "kind": "clock",
      "id": "clock",
      "size": "full",
      "title": "Desk",
      "show_seconds": true
    },
    {
      "kind": "pomodoro",
      "id": "pomodoro",
      "size": "standard",
      "label": "Focus",
      "duration_seconds": 1500
    },
    {
      "kind": "calendar",
      "id": "calendar",
      "size": "standard",
      "title": "Next",
      "source": {
        "kind": "file",
        "value": "/tmp/calendar.ics"
      },
      "refresh_minutes": 15
    }
  ],
  "widget_sizes": [
    "full",
    "standard"
  ],
  "calendar_sources": [
    {
      "kind": "file",
      "value": "/tmp/calendar.ics"
    },
    {
      "kind": "url",
      "value": "https://example.test/calendar.ics"
    }
  ],
  "runtime_states": [
    {
      "kind": "starting"
    },
    {
      "kind": "running"
    },
    {
      "kind": "paused"
    },
    {
      "kind": "error",
      "message": "error"
    }
  ],
  "connection_states": [
    {
      "kind": "disconnected",
      "reason": null
    },
    {
      "kind": "connecting"
    },
    {
      "kind": "online"
    },
    {
      "kind": "standalone"
    }
  ],
  "provider_states": [
    {
      "kind": "idle"
    },
    {
      "kind": "refreshing"
    },
    {
      "kind": "fresh"
    },
    {
      "kind": "stale",
      "message": "stale"
    },
    {
      "kind": "error",
      "message": "error"
    }
  ],
  "pomodoro_states": [
    "idle",
    "running",
    "paused",
    "completed"
  ],
  "persistence_states": [
    {
      "kind": "clean"
    },
    {
      "kind": "saving"
    },
    {
      "kind": "recoverable-error",
      "message": "error"
    }
  ],
  "validation_codes": [
    "unsupported-version",
    "empty",
    "too-long",
    "too-many",
    "duplicate-id",
    "missing-reference",
    "missing-screen",
    "duplicate-reference",
    "unsupported-size",
    "out-of-range",
    "invalid-timezone",
    "invalid-source"
  ],
  "pomodoro_actions": [
    "start",
    "pause",
    "toggle",
    "reset"
  ],
  "errors": [
    {
      "category": "invalid-payload",
      "message": "invalid"
    },
    {
      "category": "payload-too-large",
      "message": "large",
      "maximum_bytes": 65536
    },
    {
      "category": "validation",
      "message": "validation",
      "issues": [
        {
          "path": "widgets[0].size",
          "code": "unsupported-size",
          "message": "clock widgets require Full size in M3"
        }
      ]
    },
    {
      "category": "persistence",
      "message": "persistence"
    },
    {
      "category": "runtime-busy",
      "message": "busy"
    },
    {
      "category": "runtime-unavailable",
      "message": "unavailable"
    },
    {
      "category": "not-found",
      "message": "missing"
    },
    {
      "category": "device",
      "message": "device"
    },
    {
      "category": "provider",
      "message": "provider"
    },
    {
      "category": "autostart",
      "message": "autostart"
    },
    {
      "category": "window",
      "message": "window"
    },
    {
      "category": "internal",
      "message": "internal"
    }
  ],
  "draft_validation": {
    "valid": false,
    "issues": [
      {
        "path": "widgets[0].size",
        "code": "unsupported-size",
        "message": "clock widgets require Full size in M3"
      }
    ]
  },
  "config_apply_result": {
    "save": {
      "generation": 7,
      "warning": {
        "kind": "io",
        "operation": "sync config directory",
        "message": "example warning"
      }
    }
  },
  "autostart_status": {
    "enabled": true,
    "preference_enabled": false
  }
} as const satisfies IpcContractFixtures;
