import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseManifest } from "../plugins/manifest";
import { pluginFolders } from "../plugins/releases";

export const DIRECTORY_PATH = join(import.meta.dir, "../../../../docs/plugins/index.md");
const PLUGINS = join(import.meta.dir, "../../plugins");
const prose = (s: string) => s.replace(/\s+/g, " ").replace(/[\\`*_{}[\]()<>|]/g, "\\$&");

export function directoryMarkdown(root = PLUGINS): string {
  const rows = pluginFolders(root).map((id) => {
    const manifest = parseManifest(
      JSON.parse(readFileSync(join(root, id, "plugin.json"), "utf8")),
      id,
    );
    // Every listing must have an actual author guide, including the bundled example.
    readFileSync(join(root, id, "README.md"));
    return `| [${prose(manifest.label)}](../../companion/faces/plugins/${id}/README.md) | ${prose(manifest.version)} | ${prose(manifest.description)} |`;
  });
  return `# Available plugins

Plugins in this repository, linked to their own setup guides. Hosted availability
depends on the operator's reviewed deployment and withdrawal policy; listing here
does not promise hosted availability. Manifest author text is unverified attribution.
See [submitting a plugin](submitting.md) and [reviewed releases](releases.md).

<!-- Generated by companion/faces/src/author/directory.ts; checked by repository tests in CI. -->

| Plugin | Version | Description |
| --- | --- | --- |
${rows.join("\n")}
`;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    console.error("Usage: bun run src/author/directory.ts [--check]");
    process.exitCode = 1;
  } else if (args[0] === "--check") {
    if (readFileSync(DIRECTORY_PATH, "utf8") !== directoryMarkdown()) {
      console.error("Plugin directory is out of date; run bun run src/author/directory.ts");
      process.exitCode = 1;
    }
  } else {
    writeFileSync(DIRECTORY_PATH, directoryMarkdown());
  }
}
